import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0A0A0A",
        surface: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        primary: "#FFB59E",
        "primary-cta": "#FF4D00",
        "primary-container": "#FF571A",
        "primary-fixed-dim": "#FFB59E",
        "on-primary-container": "#521300",
        gold: "#D4AF37",
        silver: "#C0C0C0",
        bronze: "#CD7F32",
        secondary: "#E9C349",
        "secondary-container": "#AF8D11",
        "on-secondary-container": "#342800",
        "on-background": "#E5E2E1",
        "on-surface": "#E5E2E1",
        "on-surface-variant": "#E6BEB2",
        outline: "#AD897E",
        "outline-variant": "#5C4037",
        error: "#FFB4AB",
        "error-container": "#93000A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        gutter: "12px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "safe-margin": "20px",
        "bottom-nav-height": "72px",
      },
      fontFamily: {
        headline: ["var(--font-sora)", "Sora", "sans-serif"],
        body: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "stat-value": ["var(--font-sora)", "Sora", "sans-serif"],
        "display-stat": ["var(--font-sora)", "Sora", "sans-serif"],
        "label-caps": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-sora)", "Sora", "sans-serif"],
        "body-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["var(--font-sora)", "Sora", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "Sora", "sans-serif"],
      },
      fontSize: {
        "stat-value": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "display-stat": ["48px", { lineHeight: "48px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
